#!/bin/bash
#PBS -j oe
#PBS -l nodes=1:ppn=16:xk
#PBS -l walltime=00:30:00
#PBS -l gres=ccm
#PBS -l flags=commlocal:commtolerant
#PBS -N runpy
#PBS -q normal
#PBS -A bbcc

#source /opt/modules/default/init/bash
module list
cd /u/sciteam/chee1/github/dissertation-results/fhr_plank/fhr_plank_as_is/ 

source /projects/sciteam/bbcc/projects/openmc/openmc-parallel-python/openmc/build/myvirtualenv/bin/activate
TPN=1
NNODES=1
HOSTLIST=znodelist
LAUNCH=zstart.sh
cat $HOME/.crayccm/ccm_nodelist.$PBS_JOBID | sort -u | awk -v n=$TPN '{for(i=0;i<n;i++) print $0}' > $HOSTLIST

let NTASKS=$NNODES*$TPN

echo "#!/bin/bash
$HOME/openmpi/bin/mpirun -v -np $NTASKS --mca btl tcp,self --mca btl_tcp_if_include ipogif0 --hostfile $HOSTLIST -npernode $TPN ./a.out > job.out" > $LAUNCH
chmod 755 $LAUNCH

export PMI_NO_FORK=1

ccmrun  python openmc_input.py